language: groovy
jdk:
- oraclejdk7
script: './grailsw refresh-dependencies && ./grailsw test-app unit:'
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key:
    secure: kJNvq+FtpT13K17SEGKMvqcsrH5A2yvEL6LmcH2c7bEo16uiW5pRZKo4NCkLH/tJGtjUTF+Fe6zQuu/ZxGbQTGeu6SanTlZvZQ9fR977elToQZJnwZRAiL8lKGgWxBcCBVOD5afzKy2+sK3ZmtjmruKkzVh8K7LAdA4ft/LgoBQ=
  app: bar-o-maitre
  on:
    repo: Mathsoum/Bar-O-Maitre
    branch: master
  strategy: git

-before_script:
    - echo -e "Host vannier.pro\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

after_success:
    ./launch_sonar_analysis.sh
